

server:
  port: 8080


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/auth.practice?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12x34y56z