
server:
  port: 8091

api:
  base-path: /api/v1

spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/medup?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12x34y56z